name       : git-lfs
version    : 3.2.0
release    : 16
source     :
    - https://github.com/git-lfs/git-lfs/archive/refs/tags/v3.2.0.tar.gz : f8e6bbe043b97db8a5c16da7289e149a3fed9f4d4f11cffcc6e517c7870cd9e5
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
networking : yes
builddeps  :
    - pkgconfig(ruby-3.1)
    - git
    - golang
rundeps    :
    - git
environment: |
    export GEM_PATH=$workdir/gems
    export GEM_HOME=$workdir/gems
    export PATH=$PATH:$GEM_PATH/bin

    # the git-lfs makefile uses the system LDFLAGS by default, ypkg sets it up for C/C++ (so don't use it)
    unset LDFLAGS
setup      : |
    gem install ronn
build      : |
    %make
    %make man
install    : |
    install -Dm00755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -Dm00644 -t $installdir/usr/share/man/man1 man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man5 man/man5/*
check      : |
    %make test
