name       : git-lfs
version    : 2.7.2
release    : 6
source     :
    - https://github.com/git-lfs/git-lfs/archive/v2.7.2.tar.gz : e65659f12ec557ae8c778c01ca62d921413221864b68bd93cfa41399028ae67f
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
networking : yes
builddeps  :
    - git
    - golang
    - ruby-devel
rundeps    :
    - git
setup      : |
    export GEM_HOME=$workdir/gems
    gem install ronn
build      : |
    export GEM_PATH=$workdir/gems
    export PATH=$PATH:$GEM_PATH/bin

    # the git-lfs makefile uses the system LDFLAGS by default, ypkg sets it up for C/C++ (so don't use it)
    unset LDFLAGS

    %make
    %make man
install    : |
    install -Dm00755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -Dm00644 -t $installdir/usr/share/man/man1 man/*.1
    install -Dm00644 -t $installdir/usr/share/man/man5 man/*.5
check      : |
    %make test
