name       : git-lfs
version    : 2.1.0
release    : 5
source     :
    - https://github.com/git-lfs/git-lfs/archive/v2.1.0.tar.gz : 638e079aab661a8e4d886fd9d4ea728c5e4efcbf657ad4f5497ba39b91e91c08
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
networking : yes
builddeps  :
    - golang
    - ruby-devel
rundeps    :
    - git
setup      : |
    export GEM_HOME=$workdir/gems
    gem install ronn
build      : |
    export GEM_PATH=$workdir/gems
    export PATH=$PATH:$GEM_PATH/bin
    ./script/man
    ./script/bootstrap
install    : |
    install -Dm755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -dm644 $installdir/usr/share/man/man1
    cp man/*.1 $installdir/usr/share/man/man1
