name       : git-lfs
version    : 1.5.2
release    : 2
source     :
    - https://github.com/git-lfs/git-lfs/archive/v1.5.2.tar.gz : e452948ba1ab455516c81b41d5c85af8bba432297883e8770ade51d74762beaa
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
builddeps  :
    - golang
    - ruby-devel
rundeps    :
    - git
setup      : |
    gem install ronn
build      : |
    ./script/bootstrap
    ./script/man
install    : |
    install -Dm755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -dm644 $installdir/usr/share/man/man1
    cp man/*.1 $installdir/usr/share/man/man1