name       : git-lfs
version    : 3.4.0
release    : 19
source     :
    - https://github.com/git-lfs/git-lfs/archive/refs/tags/v3.4.0.tar.gz : fa93f65cc5c15b96037a72cf243bc2cc04c94ea5cccc346664425d6d4bac66c2
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
networking : yes
builddeps  :
    - asciidoctor
    - git
    - golang
rundeps    :
    - git
environment: |
    # the git-lfs makefile uses the system LDFLAGS by default, ypkg sets it up for C/C++ (so don't use it)
    unset LDFLAGS
build      : |
    %make
    %make man

    # Generate completions
    for sh in bash fish zsh
    do
        bin/git-lfs completion $sh > git-lfs.$sh
    done
install    : |
    install -Dm00755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -Dm00644 -t $installdir/usr/share/man/man1 man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man5 man/man5/*

    install -Dm00755 git-lfs.bash $installdir/usr/share/bash-completion/completions/git-lfs
    install -Dm00755 git-lfs.fish $installdir/usr/share/fish/vendor_completions.d/git-lfs.fish
    install -Dm00755 git-lfs.zsh $installdir/usr/share/zsh/site-functions/_git-lfs
check      : |
    %make test
