name       : git-lfs
version    : 2.12.0
release    : 11
source     :
    - https://github.com/git-lfs/git-lfs/archive/v2.12.0.tar.gz : 9971d91cd2b0dd34ccda41a3db97504bfdb4fbc23cc2ee4b6e3b9afea5643941
homepage   : https://git-lfs.github.com
license    : MIT
component  : programming.tools
summary    : Git extension for versioning large files
description: |
    Git LFS is a command line extension for managing large files with Git
networking : yes
builddeps  :
    - git
    - golang
    - ruby-devel
rundeps    :
    - git
environment: |
    export GEM_PATH=$workdir/gems
    export GEM_HOME=$workdir/gems
    export PATH=$PATH:$GEM_PATH/bin

    # the git-lfs makefile uses the system LDFLAGS by default, ypkg sets it up for C/C++ (so don't use it)
    unset LDFLAGS
setup      : |
    gem install ronn
build      : |
    %make
    %make man
install    : |
    install -Dm00755 bin/git-lfs $installdir/usr/bin/git-lfs
    install -Dm00644 -t $installdir/usr/share/man/man1 man/*.1
    install -Dm00644 -t $installdir/usr/share/man/man5 man/*.5
check      : |
    %make test
